language: python
dist: xenial

matrix:
  include:
    - python: 3.7
      env: CHECK_FORMATTING=1
    - python: 3.7
      env: CHECK_DOCS=1
    # The pypy tests are slow, so we list them first
    - python: pypy3
    - python: 3.5.0
      dist: trusty
    - python: 3.5.2
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: 3.5-dev
    - python: 3.6-dev
    - python: 3.7-dev
    - python: 3.8-dev
    - os: osx
      language: generic
      env: MACPYTHON=3.6.8
    - os: osx
      language: generic
      env: MACPYTHON=3.7.3

script:
- ci/travis.sh
